version: '3.7'

services:
  web:
    build: ./test_project
    command: python /usr/src/test_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./test_project/:/usr/src/test_project/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=polls_user
      - POSTGRES_PASSWORD=sllop
      - POSTGRES_DB=testapi
volumes:
  postgres_data:

